import brooke from './assets/brooke-cagle-h3vR1F8-caI-unsplash 1.png';
import christopher from './assets/christopher-campbell-va0YmkIFtPA-unsplash 1.png';
import ben from './assets/Фото товара.png';
import frameBrown from './assets/Frame 26.svg';
import frameGrey from './assets/Frame 26 (1).svg';
import framePink from './assets/Frame 27.svg';
import frameYellow from './assets/Frame 28.svg';

export const filter = [
  {
    title: 'Все1',
    price: 129,
    image: brooke,
    id: 0,
    index: 0,
    size: ['S', 'M', 'L', 'XL'],
    color: [frameBrown, frameGrey, framePink, frameYellow],
  },
  {
    title: 'Все2',
    price: 129,
    image: christopher,
    id: 0,
    index: 1,
    size: ['S', 'M', 'L', 'XL'],
    color: [frameBrown, frameGrey, framePink, frameYellow],
  },
  {
    title: 'Все3',
    price: 129,
    image: ben,
    id: 0,
    index: 2,
    size: ['S', 'M', 'L', 'XL'],
    color: [frameBrown, frameGrey, framePink, frameYellow],
  },
  {
    title: 'Пальто1',
    price: 129,
    image: brooke,
    id: 1,
    index: 3,
    size: ['S', 'M', 'L', 'XL'],
    color: [frameBrown, frameGrey, framePink, frameYellow],
  },
  {
    title: 'Пальто2',
    price: 129,
    image: christopher,
    id: 1,
    index: 4,
    size: ['S', 'M', 'L', 'XL'],
    color: [frameBrown, frameGrey, framePink, frameYellow],
  },
  {
    title: 'Пальто3',
    price: 129,
    image: ben,
    id: 1,
    index: 5,
    size: ['S', 'M', 'L', 'XL'],
    color: [frameBrown, frameGrey, framePink, frameYellow],
  },
  {
    title: 'Свитшоты1',
    price: 129,
    image: brooke,
    id: 2,
    index: 6,
    size: ['S', 'M', 'L', 'XL'],
    color: [frameBrown, frameGrey, framePink, frameYellow],
  },
  {
    title: 'Свитшоты2',
    price: 129,
    image: christopher,
    id: 2,
    index: 7,
    size: ['S', 'M', 'L', 'XL'],
    color: [frameBrown, frameGrey, framePink, frameYellow],
  },
  {
    title: 'Свитшоты3',
    price: 129,
    image: ben,
    id: 2,
    index: 8,
    size: ['S', 'M', 'L', 'XL'],
    color: [frameBrown, frameGrey, framePink, frameYellow],
  },
  {
    title: 'Кардиганы1',
    price: 129,
    image: brooke,
    id: 3,
    index: 9,
    size: ['S', 'M', 'L', 'XL'],
    color: [frameBrown, frameGrey, framePink, frameYellow],
  },
  {
    title: 'Кардиганы2',
    price: 129,
    image: christopher,
    id: 3,
    index: 10,
    size: ['S', 'M', 'L', 'XL'],
    color: [frameBrown, frameGrey, framePink, frameYellow],
  },
  {
    title: 'Кардиганы3',
    price: 129,
    image: ben,
    id: 3,
    index: 11,
    size: ['S', 'M', 'L', 'XL'],
    color: [frameBrown, frameGrey, framePink, frameYellow],
  },
  {
    title: 'Толстовки1',
    price: 129,
    image: brooke,
    id: 4,
    index: 12,
    size: ['S', 'M', 'L', 'XL'],
    color: [frameBrown, frameGrey, framePink, frameYellow],
  },
  {
    title: 'Толстовки2',
    price: 129,
    image: christopher,
    id: 4,
    index: 13,
    size: ['S', 'M', 'L', 'XL'],
    color: [frameBrown, frameGrey, framePink, frameYellow],
  },
  {
    title: 'Толстовки3',
    price: 129,
    image: ben,
    id: 4,
    index: 14,
    size: ['S', 'M', 'L', 'XL'],
    color: [frameBrown, frameGrey, framePink, frameYellow],
  },
];
